apiVersion: apps/v1
kind: Deployment
metadata:
  name: log680-eq8-oxygen-cs-deployment
  labels:
    app: oxygen-cs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxygen-cs
  template:
    metadata:
      labels:
        app: oxygen-cs
    spec:
      containers:
      - name: log680-oxygen-cs
        image: oxygencseq8/oxygen-cs:latest
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: '130m' # 500m limit divided by 3 (postgres, metrics and oxygencs)
            memory: '130Mi' # 500m limit divided by 3 (postgres, metrics and oxygencs)
        env:
        - name: APPLICATION_GITHUB_API_SECRET
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: env-conf-map
              key: database_port
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: env-conf-map
              key: database_host
      imagePullSecrets:
      - name: regcred
        