# Source: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: Publish Docker image

on:
  push:
    branches:
        - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: oxygencseq8/oxygen-cs:${{ github.run_id }}, oxygencseq8/oxygen-cs:latest
